version: "2"

services:

  wordpress:
    build: ./docker
    depends_on:
      - db
    env_file:
      - env

  docs:
    image: nginx
    volumes:
      - ./docs/build/html:/usr/share/nginx/html

  db:
    image: mysql:5.6
    env_file:
      - env
